spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 1234
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: test
  r2dbc:
    url: r2dbc:postgres://localhost:5432/postgres
    username: postgres
    password: 1234
    pool:
      initial-size: 10
      max-size: 20

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
